FROM alpine:3.19 AS alpine

FROM quay.io/outline/shadowbox:stable

COPY outline/ .
RUN apk add --no-cache python3 python3-dev py3-pip
RUN python3 -m venv .venv
RUN .venv/bin/python3 -m pip install -r requirements.txt
