permissions:
  packages: write
  contents: write

name: Build and Push Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build-and-push-cloak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setting Cloak version
        run: |
          git clone https://github.com/cbeuw/Cloak.git
          cd Cloak
          CLOAK_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1)).${{ github.run_number }}
          echo "CLOAK_VERSION=$CLOAK_VERSION"
          echo "CLOAK_VERSION=$CLOAK_VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Publish Docker Cloak image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/$OWNER/$REPO/dotline-server"
          VERSION=${{ env.CLOAK_VERSION }}
          IFS='.' read -r A B C D <<< "${VERSION#v}"
          VA="v$A"
          VB="v$A.$B"
          VC="v$A.$B.$C"
          VD="v$A.$B.$C.$D"
          docker build -f Dockerfile -t "$IMAGE_NAME:$VA" -t "$IMAGE_NAME:$VB" -t "$IMAGE_NAME:$VC" -t "$IMAGE_NAME:$VD" -t "$IMAGE_NAME:latest" .
          docker push "$IMAGE_NAME" --all-tags
      